spring:
  config:
    activate:
      on-profile: sleuth
  sleuth:
    enabled: false
    baggage:
      tag-fields:
        - x-user-id
        - device-id
        - lang
      remote-fields:
        - x-user-id
        - device-id
        - lang
  zipkin:
    base-url: http://localhost:9411
