spring:
  config:
    activate:
      on-profile: springdoc


springdoc:
  swagger-ui:
    groups-order: ASC
    operationsSorter: alpha
    path: /swagger-ui.html
    supportedSubmitMethods: '"get", "put", "post", "delete", "options", "head","patch", "trace"'
    tagsSorter: alpha
